spring:
  webflux:
    base-path: /shahid-notify/tunnel

server:
  port: 8080

app:
  webClient:
    connectTimeoutMillis: 5000
    responseTimeoutMillis: 5000
    readTimeoutMillis: 5000
    writeTimeoutMillis: 5000
    numberOfRetries: 1
    fixedRetryDelaySeconds: 2
    retryErrorCodes: 502, 503

actuator-logging:
  enabled: false
  metrics: 60000
  info: 60000
  health: 60000
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

